version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: leave-backend
    ports:
      - "3600:3600"
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=leave_management
    volumes:
      - ./Backend/uploads:/app/uploads

  employee-leave:
    build: ./employee-leave
    container_name: leave-employee1
    ports:
      - "8600:80"
    depends_on:
      - backend

  hr-leave:
    build: ./hr-leave
    container_name: leave-hr
    ports:
      - "8601:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: leave-postgres
    ports:
      - "5600:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: leave_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:

